name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java-test-version: [ 8, 11, 17, 21, 25 ]
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6

      - name: Setup Gradle JVM
        uses: actions/setup-java@v5
        with:
          java-version: 25
          distribution: temurin
          cache: gradle

      - name: Setup Test JVM
        uses: actions/setup-java@v5
        id: testJdk
        with:
          java-version: ${{ matrix.java-test-version }}
          distribution: temurin

      - name: Test
        run: sh ./gradlew check --no-configuration-cache --info
        env:
          org.gradle.java.home: ${{ steps.testjdk.outputs.path }}

  publish:
    needs: [ test ]
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v6

      - name: Set up JVM
        uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: temurin
          cache: gradle

      - name: Publish to Maven Central
        run: ./gradlew publish --no-configuration-cache --info
        env:
          ORG_GRADLE_PROJECT_VERSION_NAME: ${{ github.event.release.tag_name }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.central_username }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.central_password }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.signing_key }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.signing_key_password }}